#!/bin/bash

# *************************************************
# java-algs4
# Hayk Martirosyan
# -------------------
# Wrapper for java that includes algs4.jar.
# *************************************************

# This must match the install directory
INSTALL=~/MAC323

# Sets the path to the classpath libraries
jars=(.:${INSTALL}/algs4.jar:${INSTALL}/stdlib.jar)

java -cp "$jars" "$@"
